# Generated by Django 5.1.3 on 2024-12-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
